### ISSUE TITLE
FYI: project name collision

### ISSUE THREAD

**Issue by sgbeal** [tkellogg/fossil#11]
This is not an issue, per se, nor is it a request to rename your project, but it seems worth pointing out: the name [Fossil](https://fossil-scm.org) has been in active use for an SCM/DVCS since 2007.

(Edit: feel free to close this. i'd do so right now but don't want it to get overlooked before a project contributor can get around to closing it.)

**Comment by tkellogg** [comment]
Thanks for your interest. Several people have pointed this out. I'm not entirely clear on the impact of naming conflicts. Clearly naming conflicts aren't new. The US constitution contains legal framework for trademarks to support companies, because it's often critical for a name to not be confusing. While the SCM "fossil" hasn't registered a trademark, afaik, it's worth considering the impact of a naming conflict on their branding efforts.

On PyPi, here are potential naming conflicts:

* [fossil](https://pypi.org/project/Fossil/) — an SCM versioned at 0.1, I think this is not the same thing as the SCM you're referring to
* [fossil-buildbot](https://pypi.org/project/buildbot-fossil/) — a CI/CD integration for the SCM with buildbot
* [django-fossil](https://pypi.org/project/django-fossil/) — some kind of database versioning for Django. It's unclear if it's related to the fossil SCM, but I'm guessing not
* [fossil-cli](https://pypi.org/project/fossil-cli/) — the CLI for the fossil SCM. I assume it's the same SCM as you're referencing, but it's not entirely clear. Probably not official.
* [python-fossil-delta](https://pypi.org/project/python-fossil-delta/) — a Python wrapper for the compression algorithm for the Fossil SCM. This has clear links back to the fossil website, the closest thing to an official project so far in this list.

There's several more here, but they follow a similar trend.

My official position is that I don't think the naming of `fossil-mastodon` is confusing, especially given the other hits in PyPi. I don't think it infringes on Fossil SCM's ability to operate, acquire users, or earn trust from their users. If the maintainers of Fossil SCM disagree, then I'm open to discussing a rename. More likely, there other ways to clarify the difference between the projects.

**Comment by sgbeal** [comment]
> If the maintainers of Fossil SCM disagree, then I'm open to discussing a rename.

FWIW, i'm one of those devs, so felt compelled to point it out ;). We're not contesting the name or anything of the sort, though.

Happy Hacking!
